services:
  backend:
    build: ./Techdome-backend
    ports:
      - "5050:5050" 
    networks:
      - techdome_mern_network
    environment:
      DB: mongodb://mongodb:27017/mydatabase 
  
    depends_on:
      - mongodb

  frontend:
    build: ./Techdome-frontend
    ports:
      - "3000:3000"  
    networks:
      - techdome_mern_network
    environment:
      REACT_APP_API_URL: http://backend:5050 

  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - techdome_mern_network
    volumes:
      - mongo-data:/data/db  

networks:
  techdome_mern_network:
    driver: bridge 

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally

